export const LOAD_PAGE_DATA = "/STARWARINFO/LOAD_PAGE_DATA";
export const PAGE_DATA_LOADED = "/STARWARINFO/PAGE_DATA_LOADED";
export const LOAD_CAT_ITEMS = "/STARWARINFO/LOAD_CAT_ITEMS";
export const CAT_DATA_LOADED = "/STARWARINFO/CAT_DATA_LOADED";
export const LOAD_ITEM_DATA = "/STARWARINFO/LOAD_ITEM_DATA";
export const ITEM_DATA_LOADED = "/STARWARINFO/ITEM_DATA_LOADED";