export const LOAD_PAGE_DATA = "/EMPLOYEE/LISTING/LOAD_PAGE_DATA";
export const PAGE_DATA_LOADED = "/EMPLOYEE/LISTING/PAGE_DATA_LOADED"; 
export const DELETE_EMPLOYEE = "/EMPLOYEE/LISTING/DELETE_EMPLOYEE"; 