export const CREATE_EMPLOYEE_DATA = "/EMPLOYEE/ADDEDIT/CREATE_EMPLOYEE_DATA";
export const LOAD_EMPLOYEE_DATA = "/EMPLOYEE/ADDEDIT/LOAD_EMPLOYEE_DATA";
export const LOAD_EMPLOYEE_SUCCESS = "/EMPLOYEE/ADDEDIT/LOAD_EMPLOYEE_SUCCESS";
export const EDIT_EMPLOYEE_DATA = "/EMPLOYEE/ADDEDIT/EDIT_EMPLOYEE_DATA";
export const LOAD_DEFAULT_STATE = "/EMPLOYEE/ADDEDIT/LOAD_DEFAULT_STATE";